### ISSUE TITLE
Can you explain what i'm looking at on the screen in the picture?

### ISSUE THREAD

**Issue by meffect** [ciembor/4bit#28]
I have no idea the picture, what the rows and columns mean. And the picture almost looks like a terminal window I can type in, but I cant. so I think am I supposed to be able to type in there?

It's extremely confusing this thing. I dont see how it benefits me at all. I dont see how i can generate something and know I'll be happy with the final result because either, it doesnt show enough mockups, or not enough documentation to explain how to use this tool

**Comment by ciembor** [comment]
Hello,

The thing that looks like a terminal is presenting the color scheme. You can change colors using controls on the right. Than you can download the scheme for your terminal clicking button "Get Scheme" in the top right corner. It's explained in documentation (https://github.com/ciembor/4bit#for-users). There is currently a bug since some version of Google Chrome, so if the color scheme doestn't open after clicking the button, you will have to right click, copy the link and paste it in new window. Thanks for your feedback. I hope I helped and you are not a troll.

Cheers,
- Maciej

**Comment by meffect** [comment]
I'm not a troll I just sound like one sometimes lol.. hmmmm... I need to work on that
