### ISSUE TITLE
Where to save mintty themes?

### ISSUE THREAD

**Issue by sigmap** [ciembor/4bit#33]
Did not see anything on where to save them

**Comment by ciembor** [comment]
I don't use mintty, but I believe you should add it to ~/.minttyrc.

**Comment by mintty** [comment]
Since mintty 2.4.0, you can also place the file in a dedicated `themes` subdirectory of a mintty config directory (various options, check the manual).
Also, mintty has a direct link to the Color Scheme Designer in the Options dialog, and you can drag and drop the "Get Scheme" link to it or into the Theme field, and save it from there, without handling any files explicitly.
